#!/usr/bin/env node
// Extracts ABIs from forge artifacts into the frontend as typed consts,
// so the UI can never drift from the deployed contracts.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const out = resolve(root, "../web/lib/abi.ts");

const targets = [
  ["launchpadAbi", "out/ArcLaunchpad.sol/ArcLaunchpad.json"],
  ["swapRouterAbi", "out/ArcSwapRouter.sol/ArcSwapRouter.json"],
  ["launchTokenAbi", "out/LaunchToken.sol/LaunchToken.json"],
  ["uniswapV3PoolAbi", "out/IUniswapV3.sol/IUniswapV3Pool.json"],
  ["erc20Abi", "out/LaunchToken.sol/LaunchToken.json"],
];

let src = `// GENERATED by contracts/script/gen-abi.mjs — do not edit by hand.\n// Regenerate with: pnpm abi\n\n`;

for (const [name, path] of targets) {
  const artifact = JSON.parse(readFileSync(resolve(root, path), "utf8"));
  src += `export const ${name} = ${JSON.stringify(artifact.abi)} as const;\n\n`;
}

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, src);
console.log(`wrote ${out}`);
