#!/usr/bin/env node
/**
 * Regenerate web/lib/abi.ts from compiled artifacts.
 *
 * The file was hand-maintained and silently fell behind the contracts -- the
 * frontend had no idea referrals or fee escrow existed. Generating it means a
 * `forge build` away from a stale frontend is a diff, not a mystery.
 *
 * Usage: node scripts/sync-abi.mjs   (run from the repo root, after forge build)
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");
const uni = join(root, "contracts", "tools", "node_modules", "@uniswap", "v3-core", "artifacts", "contracts");

/** Only the pool members the app actually reads; the full ABI is enormous. */
const POOL_KEEP = new Set([
  "burn", "collect", "fee", "initialize", "liquidity", "mint", "positions",
  "slot0", "swap", "tickSpacing", "token0", "token1",
  // Needed to compute fees that have accrued but not yet been credited.
  "ticks", "feeGrowthGlobal0X128", "feeGrowthGlobal1X128",
]);

const ERC20_KEEP = new Set(["name", "symbol", "decimals", "totalSupply", "balanceOf", "allowance", "approve", "transfer"]);

function load(path, name) {
  const file = join(path, `${name}.sol`, `${name}.json`);
  if (!existsSync(file)) throw new Error(`missing artifact: ${file}`);
  return JSON.parse(readFileSync(file, "utf8")).abi;
}

const keep = (abi, names) =>
  abi.filter((e) => (e.type === "function" ? names.has(e.name) : e.type === "event" || e.type === "error"));

const banner = `// GENERATED by scripts/sync-abi.mjs -- do not edit by hand.
// Run \`forge build\` in contracts/, then \`node scripts/sync-abi.mjs\` from the repo root.
`;

const parts = [banner];
const emit = (name, abi) =>
  parts.push(`export const ${name} = ${JSON.stringify(abi)} as const;\n`);

emit("launchpadAbi", load(out, "ArcLaunchpad"));
emit("swapRouterAbi", load(out, "ArcSwapRouter"));
emit("launchTokenAbi", load(out, "LaunchToken"));
emit("uniswapV3PoolAbi", keep(load(uni, "UniswapV3Pool"), POOL_KEEP).filter((e) => e.type === "function"));
emit("erc20Abi", keep(load(out, "LaunchToken"), ERC20_KEEP).filter((e) => e.type === "function"));

writeFileSync(join(root, "web", "lib", "abi.ts"), parts.join("\n"));
console.log("wrote web/lib/abi.ts");
