#!/usr/bin/env node
/**
 * Regenerate web/lib/abi.ts from compiled artifacts.
 *
 * The file was hand-maintained and silently fell behind the contracts -- the
 * frontend had no idea referrals or fee escrow existed. Generating it means a
 * `forge build` away from a stale frontend is a diff, not a mystery.
 *
 * Usage: node scripts/sync-abi.mjs   (run from the repo root, after forge build)
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");
/** v4 keeps every pool inside one manager, so the app reads pool state through
 *  StateView and prices through the quoter rather than from a pool contract. */
const STATE_VIEW_KEEP = new Set([
  "getSlot0", "getLiquidity", "getPositionInfo", "getPositionLiquidity",
  // v4 hands back the growth inside a range directly, so the app no longer
  // reimplements Uniswap's tick math to work out uncollected fees.
  "getFeeGrowthInside", "getFeeGrowthGlobals", "getTickInfo",
]);

const ERC20_KEEP = new Set(["name", "symbol", "decimals", "totalSupply", "balanceOf", "allowance", "approve", "transfer"]);

function load(path, name) {
  const file = join(path, `${name}.sol`, `${name}.json`);
  if (!existsSync(file)) throw new Error(`missing artifact: ${file}`);
  return JSON.parse(readFileSync(file, "utf8")).abi;
}

const keep = (abi, names) =>
  abi.filter((e) => (e.type === "function" ? names.has(e.name) : e.type === "event" || e.type === "error"));

const banner = `// GENERATED by scripts/sync-abi.mjs -- do not edit by hand.
// Run \`forge build\` in contracts/, then \`node scripts/sync-abi.mjs\` from the repo root.
`;

const parts = [banner];
const emit = (name, abi) =>
  parts.push(`export const ${name} = ${JSON.stringify(abi)} as const;\n`);

emit("launchpadAbi", load(out, "ArcLaunchpad"));
emit("swapRouterAbi", load(out, "TsukiRouter"));
emit("launchTokenAbi", load(out, "LaunchToken"));
emit("curveAbi", load(out, "TsukiCurve"));
emit("curveTokenAbi", load(out, "CurveToken"));
emit("hookAbi", load(out, "TsukiHook"));
emit("poolManagerAbi", load(out, "PoolManager"));
emit("stateViewAbi", keep(load(out, "StateView"), STATE_VIEW_KEEP).filter((e) => e.type === "function"));
emit("quoterAbi", load(out, "V4Quoter"));
emit("erc20Abi", keep(load(out, "LaunchToken"), ERC20_KEEP).filter((e) => e.type === "function"));

writeFileSync(join(root, "web", "lib", "abi.ts"), parts.join("\n"));
console.log("wrote web/lib/abi.ts");
